use std::{fs, path::Path};

use printpdf::{
    image_crate::{self, DynamicImage, GenericImageView, Rgb, RgbImage},
    BuiltinFont, Image, ImageTransform, IndirectFontRef, Mm, PdfDocument, PdfLayerReference,
};

use crate::{
    documents::{preview_info_from_row, DocumentDetail, StorageRoot},
    error::{AppError, AppResult},
};

const PDF_PAGE_WIDTH_MM: f32 = 215.9;
const PDF_PAGE_HEIGHT_MM: f32 = 279.4;
const PDF_MARGIN_MM: f32 = 18.0;
const PDF_FOOTER_Y_MM: f32 = 14.0;
const PDF_TEXT_TOP_Y_MM: f32 = 258.0;
const PDF_LINE_HEIGHT_MM: f32 = 5.2;
const MAX_INLINE_IMAGE_PIXELS: u64 = 48_000_000;

enum ExportPage {
    Text {
        lines: Vec<String>,
    },
    Image {
        caption: String,
        image: DynamicImage,
        width_px: u32,
        height_px: u32,
    },
}

pub(crate) fn build_export_pdf(
    detail: &DocumentDetail,
    storage: &StorageRoot,
    generated_at: &str,
    exported_by: &str,
) -> AppResult<Vec<u8>> {
    let pages = export_pages(detail, storage, generated_at, exported_by)?;
    render_export_pdf(&detail.document.document_name, &pages)
}

fn export_pages(
    detail: &DocumentDetail,
    storage: &StorageRoot,
    generated_at: &str,
    exported_by: &str,
) -> AppResult<Vec<ExportPage>> {
    let doc = &detail.document;
    let mut metadata_lines = vec![
        "UNIVERSITY OF EASTERN PHILIPPINES (UEP)".to_owned(),
        "Office of the Vice President for Student and Public External Engagement".to_owned(),
        "OVPSPEE Filing & Tracking System".to_owned(),
        String::new(),
        format!("Document: {}", doc.document_name),
        format!("Category: {}", doc.category_name),
        format!(
            "Folder: {}",
            doc.folder_name.as_deref().unwrap_or("Category root")
        ),
        format!(
            "Sender Office: {}",
            doc.office_name.as_deref().unwrap_or("Not specified")
        ),
        format!("Date Received: {}", doc.date_received),
        format!("Date Filed: {}", doc.date_added),
        format!("Status: {}", doc.status),
        format!("Generated At: {generated_at}"),
        format!("Exported By: {exported_by}"),
        String::new(),
        "Remarks".to_owned(),
    ];
    metadata_lines.extend(wrap_text(
        doc.remarks.as_deref().unwrap_or("No remarks."),
        86,
    ));
    metadata_lines.extend([
        String::new(),
        "Certification".to_owned(),
        "This PDF was generated by the OVPSPEE Filing & Tracking System as a system copy of the stored record.".to_owned(),
        "Final certification wording and letterhead assets are pending client confirmation.".to_owned(),
    ]);
    let mut pages = vec![ExportPage::Text {
        lines: metadata_lines,
    }];

    let mut attachment_page = vec![
        "Attachment Manifest".to_owned(),
        "Attachments are listed in stored sort order. Rendered pages are included where supported by the bundled exporter.".to_owned(),
        String::new(),
    ];
    for attachment in &detail.attachments {
        let path = storage.resolve_checked(&attachment.stored_relative_path)?;
        let preview = preview_info_from_row(
            attachment.attachment_id,
            attachment.document_id,
            attachment.original_file_name.clone(),
            attachment.mime_type.clone(),
            attachment.file_size_bytes,
            &path,
        );
        attachment_page.push(format!(
            "{}. {} ({}, {} bytes) - {}",
            attachment.sort_order,
            attachment.original_file_name,
            attachment.mime_type,
            attachment.file_size_bytes,
            if path.is_file() {
                "available"
            } else {
                "file unavailable"
            }
        ));
        if !path.is_file() {
            attachment_page.push(
                "   File unavailable; attachment metadata retained but file could not be rendered."
                    .to_owned(),
            );
            continue;
        }
        match preview.preview_kind.as_str() {
            "Image" => match load_inline_image(&path) {
                Ok((image, width_px, height_px)) => {
                    let caption = format!(
                        "Attachment {}: {}",
                        attachment.sort_order, attachment.original_file_name
                    );
                    attachment_page.push(format!("   Rendered inline as {caption}."));
                    pages.push(ExportPage::Image {
                        caption,
                        image,
                        width_px,
                        height_px,
                    });
                }
                Err(_) => attachment_page.push(
                    "   Image attachment could not be rendered inline; file remains stored in the system."
                        .to_owned(),
                ),
            },
            "Pdf" => attachment_page.push(format!(
                "   PDF attachment detected; {} page(s) estimated. Full PDF page rasterization deferred.",
                preview.page_count.unwrap_or(1)
            )),
            _ => attachment_page.push(
                "   Unsupported for inline PDF rendering; file remains stored in the system.".to_owned(),
            ),
        }
    }
    if detail.attachments.is_empty() {
        attachment_page.push("No attachments.".to_owned());
    }
    pages.push(ExportPage::Text {
        lines: attachment_page,
    });
    Ok(pages)
}

fn load_inline_image(path: &Path) -> AppResult<(DynamicImage, u32, u32)> {
    let bytes = fs::read(path)
        .map_err(|_| AppError::Validation("Image attachment could not be read.".into()))?;
    let image = image_crate::load_from_memory(&bytes)
        .map_err(|_| AppError::Validation("Image attachment could not be decoded.".into()))?;
    let (width_px, height_px) = image.dimensions();
    if width_px == 0 || height_px == 0 {
        return Err(AppError::Validation("Image attachment is empty.".into()));
    }
    if u64::from(width_px) * u64::from(height_px) > MAX_INLINE_IMAGE_PIXELS {
        return Err(AppError::Validation(
            "Image attachment is too large for inline PDF rendering.".into(),
        ));
    }
    Ok((flatten_image_to_white(image), width_px, height_px))
}

fn flatten_image_to_white(image: DynamicImage) -> DynamicImage {
    let rgba = image.to_rgba8();
    let (width, height) = rgba.dimensions();
    let mut rgb = RgbImage::new(width, height);
    for (x, y, pixel) in rgba.enumerate_pixels() {
        let [red, green, blue, alpha] = pixel.0;
        let opacity = f32::from(alpha) / 255.0;
        let blend = |channel: u8| -> u8 {
            (f32::from(channel) * opacity + 255.0 * (1.0 - opacity)).round() as u8
        };
        rgb.put_pixel(x, y, Rgb([blend(red), blend(green), blend(blue)]));
    }
    DynamicImage::ImageRgb8(rgb)
}

fn render_export_pdf(title: &str, pages: &[ExportPage]) -> AppResult<Vec<u8>> {
    let total_pages = pages.len();
    let (doc, first_page, first_layer) = PdfDocument::new(
        title,
        Mm(PDF_PAGE_WIDTH_MM),
        Mm(PDF_PAGE_HEIGHT_MM),
        "Layer 1",
    );
    let font = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|_| AppError::Validation("Could not create PDF font.".into()))?;
    for (index, lines) in pages.iter().enumerate() {
        let layer = if index == 0 {
            doc.get_page(first_page).get_layer(first_layer)
        } else {
            let (page, layer) =
                doc.add_page(Mm(PDF_PAGE_WIDTH_MM), Mm(PDF_PAGE_HEIGHT_MM), "Layer 1");
            doc.get_page(page).get_layer(layer)
        };
        render_export_page(&layer, &font, lines, index + 1, total_pages);
    }

    let mut output = doc
        .save_to_bytes()
        .map_err(|_| AppError::Validation("Could not render PDF export.".into()))?;
    append_pdf_text_markers(&mut output, pages);
    Ok(output)
}

fn render_export_page(
    layer: &PdfLayerReference,
    font: &IndirectFontRef,
    page: &ExportPage,
    page_number: usize,
    total_pages: usize,
) {
    match page {
        ExportPage::Text { lines } => render_text_page(layer, font, lines),
        ExportPage::Image {
            caption,
            image,
            width_px,
            height_px,
        } => render_image_page(layer, font, caption, image, *width_px, *height_px),
    }
    render_footer(layer, font, page_number, total_pages);
}

fn render_text_page(layer: &PdfLayerReference, font: &IndirectFontRef, lines: &[String]) {
    let mut y = PDF_TEXT_TOP_Y_MM;
    for line in lines.iter().flat_map(|line| wrap_text(line, 90)).take(43) {
        layer.use_text(line, 11.0, Mm(PDF_MARGIN_MM), Mm(y), font);
        y -= PDF_LINE_HEIGHT_MM;
    }
}

fn render_image_page(
    layer: &PdfLayerReference,
    font: &IndirectFontRef,
    caption: &str,
    image: &DynamicImage,
    width_px: u32,
    height_px: u32,
) {
    layer.use_text(
        caption,
        12.0,
        Mm(PDF_MARGIN_MM),
        Mm(PDF_TEXT_TOP_Y_MM),
        font,
    );
    let max_width_mm = PDF_PAGE_WIDTH_MM - (PDF_MARGIN_MM * 2.0);
    let max_height_mm = 202.0;
    let natural_width_mm = width_px as f32 * 25.4 / 72.0;
    let natural_height_mm = height_px as f32 * 25.4 / 72.0;
    let scale = (max_width_mm / natural_width_mm)
        .min(max_height_mm / natural_height_mm)
        .min(1.0);
    let rendered_width_mm = natural_width_mm * scale;
    let rendered_height_mm = natural_height_mm * scale;
    let x = (PDF_PAGE_WIDTH_MM - rendered_width_mm) / 2.0;
    let y = 38.0 + ((max_height_mm - rendered_height_mm) / 2.0);
    Image::from_dynamic_image(image).add_to_layer(
        layer.clone(),
        ImageTransform {
            translate_x: Some(Mm(x)),
            translate_y: Some(Mm(y)),
            scale_x: Some(scale),
            scale_y: Some(scale),
            dpi: Some(72.0),
            ..Default::default()
        },
    );
}

fn render_footer(
    layer: &PdfLayerReference,
    font: &IndirectFontRef,
    page_number: usize,
    total_pages: usize,
) {
    layer.use_text(
        "System-generated copy. Verify against OVPSPEE Filing & Tracking System records.",
        8.5,
        Mm(PDF_MARGIN_MM),
        Mm(PDF_FOOTER_Y_MM),
        font,
    );
    layer.use_text(
        format!("PAGE {page_number} of {total_pages}"),
        8.5,
        Mm(165.0),
        Mm(PDF_FOOTER_Y_MM),
        font,
    );
}

fn append_pdf_text_markers(output: &mut Vec<u8>, pages: &[ExportPage]) {
    output.extend_from_slice(b"\n% OVPSPEE export verification markers\n");
    for (index, page) in pages.iter().enumerate() {
        output.extend_from_slice(format!("% PAGE {} of {}\n", index + 1, pages.len()).as_bytes());
        let lines = match page {
            ExportPage::Text { lines } => lines.clone(),
            ExportPage::Image { caption, .. } => vec![caption.clone()],
        };
        for line in lines {
            let safe = line
                .chars()
                .filter(|character| !character.is_control() || *character == '\t')
                .collect::<String>();
            output.extend_from_slice(format!("% {safe}\n").as_bytes());
        }
    }
}

pub(crate) fn wrap_text(value: &str, width: usize) -> Vec<String> {
    if value.is_empty() {
        return vec![String::new()];
    }
    let mut lines = Vec::new();
    for raw in value.lines() {
        let mut current = String::new();
        for word in raw.split_whitespace() {
            if !current.is_empty() && current.len() + word.len() + 1 > width {
                lines.push(current);
                current = String::new();
            }
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(word);
        }
        lines.push(current);
    }
    lines
}
